FROM node:20-alpine

WORKDIR /app

ARG baseUrl
ARG allowedHost

ENV baseUrl=$baseUrl
ENV allowedHost=$allowedHost

COPY ./package*.json ./
RUN npm ci

COPY . .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--port=5173"]