version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: RoomFunds-backend
    command: gunicorn RoomFunds.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - static_volume:/app/static
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: RoomFunds-frontend
    command: npm run preview
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

volumes:
  static_volume:
