/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '.././client';
import type { ErrorType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const whoamiRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/whoami/`, method: 'GET', signal
    },
      options);
    }
  

export const getWhoamiRetrieveQueryKey = () => {
    return [`/whoami/`] as const;
    }

    
export const getWhoamiRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof whoamiRetrieve>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoamiRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWhoamiRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof whoamiRetrieve>>> = ({ signal }) => whoamiRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof whoamiRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WhoamiRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof whoamiRetrieve>>>
export type WhoamiRetrieveQueryError = ErrorType<unknown>


export function useWhoamiRetrieve<TData = Awaited<ReturnType<typeof whoamiRetrieve>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoamiRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof whoamiRetrieve>>,
          TError,
          Awaited<ReturnType<typeof whoamiRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWhoamiRetrieve<TData = Awaited<ReturnType<typeof whoamiRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoamiRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof whoamiRetrieve>>,
          TError,
          Awaited<ReturnType<typeof whoamiRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWhoamiRetrieve<TData = Awaited<ReturnType<typeof whoamiRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoamiRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWhoamiRetrieve<TData = Awaited<ReturnType<typeof whoamiRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoamiRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWhoamiRetrieveQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



