FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN apk add --no-cache gcc musl-dev libpq-dev postgresql-dev

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

RUN mkdir -p /app/static

CMD ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn RoomFunds.wsgi:application -b 0.0.0.0:8000"]