# Generated by Django 5.2 on 2025-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logincode",
            name="access_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="logincode",
            name="refresh_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
