# Generated by Django 5.2.5 on 2025-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0002_logincode_access_token_logincode_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logincode",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
