/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Category,
  Group
} from '.././model';

import { customInstance } from '.././client';
import type { ErrorType , BodyType } from '.././client';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const apiExpenseRetrieve = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/expense/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getApiExpenseRetrieveQueryKey = (id: number,) => {
    return [`/api/expense/${id}`] as const;
    }

    
export const getApiExpenseRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiExpenseRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiExpenseRetrieve>>> = ({ signal }) => apiExpenseRetrieve(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiExpenseRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof apiExpenseRetrieve>>>
export type ApiExpenseRetrieveQueryError = ErrorType<unknown>


export function useApiExpenseRetrieve<TData = Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiExpenseRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiExpenseRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiExpenseRetrieve<TData = Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiExpenseRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiExpenseRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiExpenseRetrieve<TData = Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiExpenseRetrieve<TData = Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpenseRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiExpenseRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const apiExpenseUpdate = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/expense/${id}`, method: 'PUT'
    },
      options);
    }
  


export const getApiExpenseUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiExpenseUpdate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiExpenseUpdate>>, TError,{id: number}, TContext> => {

const mutationKey = ['apiExpenseUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiExpenseUpdate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  apiExpenseUpdate(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiExpenseUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof apiExpenseUpdate>>>
    
    export type ApiExpenseUpdateMutationError = ErrorType<unknown>

    export const useApiExpenseUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiExpenseUpdate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiExpenseUpdate>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getApiExpenseUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const apiExpenseDestroy = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/expense/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getApiExpenseDestroyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiExpenseDestroy>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiExpenseDestroy>>, TError,{id: number}, TContext> => {

const mutationKey = ['apiExpenseDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiExpenseDestroy>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  apiExpenseDestroy(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiExpenseDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof apiExpenseDestroy>>>
    
    export type ApiExpenseDestroyMutationError = ErrorType<unknown>

    export const useApiExpenseDestroy = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiExpenseDestroy>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiExpenseDestroy>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getApiExpenseDestroyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const apiExpensesRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/expenses`, method: 'GET', signal
    },
      options);
    }
  

export const getApiExpensesRetrieveQueryKey = () => {
    return [`/api/expenses`] as const;
    }

    
export const getApiExpensesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiExpensesRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiExpensesRetrieve>>> = ({ signal }) => apiExpensesRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiExpensesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof apiExpensesRetrieve>>>
export type ApiExpensesRetrieveQueryError = ErrorType<unknown>


export function useApiExpensesRetrieve<TData = Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiExpensesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiExpensesRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiExpensesRetrieve<TData = Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiExpensesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiExpensesRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiExpensesRetrieve<TData = Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiExpensesRetrieve<TData = Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiExpensesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiExpensesRetrieveQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const apiExpensesCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/expenses`, method: 'POST', signal
    },
      options);
    }
  


export const getApiExpensesCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiExpensesCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiExpensesCreate>>, TError,void, TContext> => {

const mutationKey = ['apiExpensesCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiExpensesCreate>>, void> = () => {
          

          return  apiExpensesCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiExpensesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiExpensesCreate>>>
    
    export type ApiExpensesCreateMutationError = ErrorType<unknown>

    export const useApiExpensesCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiExpensesCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiExpensesCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApiExpensesCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const apiGroupCategoriesRetrieve = (
    groupName: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Category>(
      {url: `/api/group/${groupName}/categories`, method: 'GET', signal
    },
      options);
    }
  

export const getApiGroupCategoriesRetrieveQueryKey = (groupName: string,) => {
    return [`/api/group/${groupName}/categories`] as const;
    }

    
export const getApiGroupCategoriesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError = ErrorType<unknown>>(groupName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiGroupCategoriesRetrieveQueryKey(groupName);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>> = ({ signal }) => apiGroupCategoriesRetrieve(groupName, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(groupName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiGroupCategoriesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>>
export type ApiGroupCategoriesRetrieveQueryError = ErrorType<unknown>


export function useApiGroupCategoriesRetrieve<TData = Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError = ErrorType<unknown>>(
 groupName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiGroupCategoriesRetrieve<TData = Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError = ErrorType<unknown>>(
 groupName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiGroupCategoriesRetrieve<TData = Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError = ErrorType<unknown>>(
 groupName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiGroupCategoriesRetrieve<TData = Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError = ErrorType<unknown>>(
 groupName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupCategoriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiGroupCategoriesRetrieveQueryOptions(groupName,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const apiGroupCategoriesCreate = (
    groupName: string,
    category: BodyType<Category>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Category>(
      {url: `/api/group/${groupName}/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: category, signal
    },
      options);
    }
  


export const getApiGroupCategoriesCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupCategoriesCreate>>, TError,{groupName: string;data: BodyType<Category>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiGroupCategoriesCreate>>, TError,{groupName: string;data: BodyType<Category>}, TContext> => {

const mutationKey = ['apiGroupCategoriesCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiGroupCategoriesCreate>>, {groupName: string;data: BodyType<Category>}> = (props) => {
          const {groupName,data} = props ?? {};

          return  apiGroupCategoriesCreate(groupName,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiGroupCategoriesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiGroupCategoriesCreate>>>
    export type ApiGroupCategoriesCreateMutationBody = BodyType<Category>
    export type ApiGroupCategoriesCreateMutationError = ErrorType<unknown>

    export const useApiGroupCategoriesCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupCategoriesCreate>>, TError,{groupName: string;data: BodyType<Category>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiGroupCategoriesCreate>>,
        TError,
        {groupName: string;data: BodyType<Category>},
        TContext
      > => {

      const mutationOptions = getApiGroupCategoriesCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const apiGroupRetrieve = (
    name: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Group>(
      {url: `/api/group/${name}`, method: 'GET', signal
    },
      options);
    }
  

export const getApiGroupRetrieveQueryKey = (name: string,) => {
    return [`/api/group/${name}`] as const;
    }

    
export const getApiGroupRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof apiGroupRetrieve>>, TError = ErrorType<unknown>>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiGroupRetrieveQueryKey(name);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiGroupRetrieve>>> = ({ signal }) => apiGroupRetrieve(name, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(name), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiGroupRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiGroupRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof apiGroupRetrieve>>>
export type ApiGroupRetrieveQueryError = ErrorType<unknown>


export function useApiGroupRetrieve<TData = Awaited<ReturnType<typeof apiGroupRetrieve>>, TError = ErrorType<unknown>>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiGroupRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiGroupRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiGroupRetrieve<TData = Awaited<ReturnType<typeof apiGroupRetrieve>>, TError = ErrorType<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiGroupRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiGroupRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiGroupRetrieve<TData = Awaited<ReturnType<typeof apiGroupRetrieve>>, TError = ErrorType<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiGroupRetrieve<TData = Awaited<ReturnType<typeof apiGroupRetrieve>>, TError = ErrorType<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiGroupRetrieveQueryOptions(name,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const apiGroupUpdate = (
    name: string,
    group: BodyType<NonReadonly<Group>>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Group>(
      {url: `/api/group/${name}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: group
    },
      options);
    }
  


export const getApiGroupUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupUpdate>>, TError,{name: string;data: BodyType<NonReadonly<Group>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiGroupUpdate>>, TError,{name: string;data: BodyType<NonReadonly<Group>>}, TContext> => {

const mutationKey = ['apiGroupUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiGroupUpdate>>, {name: string;data: BodyType<NonReadonly<Group>>}> = (props) => {
          const {name,data} = props ?? {};

          return  apiGroupUpdate(name,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiGroupUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof apiGroupUpdate>>>
    export type ApiGroupUpdateMutationBody = BodyType<NonReadonly<Group>>
    export type ApiGroupUpdateMutationError = ErrorType<unknown>

    export const useApiGroupUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupUpdate>>, TError,{name: string;data: BodyType<NonReadonly<Group>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiGroupUpdate>>,
        TError,
        {name: string;data: BodyType<NonReadonly<Group>>},
        TContext
      > => {

      const mutationOptions = getApiGroupUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const apiGroupDestroy = (
    name: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/group/${name}`, method: 'DELETE'
    },
      options);
    }
  


export const getApiGroupDestroyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupDestroy>>, TError,{name: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiGroupDestroy>>, TError,{name: string}, TContext> => {

const mutationKey = ['apiGroupDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiGroupDestroy>>, {name: string}> = (props) => {
          const {name} = props ?? {};

          return  apiGroupDestroy(name,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiGroupDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof apiGroupDestroy>>>
    
    export type ApiGroupDestroyMutationError = ErrorType<unknown>

    export const useApiGroupDestroy = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupDestroy>>, TError,{name: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiGroupDestroy>>,
        TError,
        {name: string},
        TContext
      > => {

      const mutationOptions = getApiGroupDestroyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const apiGroupsRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Group>(
      {url: `/api/groups`, method: 'GET', signal
    },
      options);
    }
  

export const getApiGroupsRetrieveQueryKey = () => {
    return [`/api/groups`] as const;
    }

    
export const getApiGroupsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiGroupsRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiGroupsRetrieve>>> = ({ signal }) => apiGroupsRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiGroupsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof apiGroupsRetrieve>>>
export type ApiGroupsRetrieveQueryError = ErrorType<unknown>


export function useApiGroupsRetrieve<TData = Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiGroupsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiGroupsRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiGroupsRetrieve<TData = Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiGroupsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiGroupsRetrieve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiGroupsRetrieve<TData = Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiGroupsRetrieve<TData = Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiGroupsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiGroupsRetrieveQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const apiGroupsCreate = (
    group: BodyType<NonReadonly<Group>>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Group>(
      {url: `/api/groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: group, signal
    },
      options);
    }
  


export const getApiGroupsCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupsCreate>>, TError,{data: BodyType<NonReadonly<Group>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof apiGroupsCreate>>, TError,{data: BodyType<NonReadonly<Group>>}, TContext> => {

const mutationKey = ['apiGroupsCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiGroupsCreate>>, {data: BodyType<NonReadonly<Group>>}> = (props) => {
          const {data} = props ?? {};

          return  apiGroupsCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApiGroupsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiGroupsCreate>>>
    export type ApiGroupsCreateMutationBody = BodyType<NonReadonly<Group>>
    export type ApiGroupsCreateMutationError = ErrorType<unknown>

    export const useApiGroupsCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiGroupsCreate>>, TError,{data: BodyType<NonReadonly<Group>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiGroupsCreate>>,
        TError,
        {data: BodyType<NonReadonly<Group>>},
        TContext
      > => {

      const mutationOptions = getApiGroupsCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    