/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface Category {
  /** @maxLength 255 */
  name: string;
  description?: string;
  group_name: string;
}
