/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface Expense {
  readonly user: string;
  group: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount: string;
  readonly category: string;
  category_input?: string;
  description?: string;
  date: string;
}
