/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface Group {
  /** @maxLength 100 */
  name: string;
  description?: string;
  readonly owner: string;
  readonly moderators: string;
  readonly members: string;
}
