/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface Group {
  /** @maxLength 100 */
  name: string;
  readonly slug: string;
  description?: string;
  readonly owner: string;
  readonly moderators: readonly string[];
  readonly members: readonly string[];
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  readonly total_amount: string;
}
