# Generated by Django 5.2 on 2025-06-06 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_expense_category_obj"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="category_obj",
            new_name="category",
        ),
    ]
