# Generated by Django 5.2.5 on 2025-09-30 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_category_obj_expense_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
    ]
