# Generated by Django 5.2.5 on 2025-09-30 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_group_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="expense_groups",
                through="core.GroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
