# Generated by Django 5.2.5 on 2025-09-30 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_group_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="moderators",
        ),
    ]
