# Generated by Django 5.2.5 on 2025-09-30 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_group_moderators"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
